### PR TITLE
Handle negative resolution when loading tiff

### PR DESCRIPTION
**Pull request by philippjfr**
Ensures that negative resolutions flip the coordinates inside a tiff, ensuring that the image displays with the correct orientation by default.

### CODE REVIEW

**Comment by jlstevens** [comment]
Thanks!

One more general issue (that may not be in the scope of this PR) is that when using tools like `intake`, you don't get a 'tif' file to load. This is a bit of a pain as the things that `load_tiff` does (transfer crs, apply `res`, fix coordinate ordering) are really useful and it would be nice to have similar functionality when starting with an `xarray` data structure.

**Comment by philippjfr** [comment]
I've now added factored out a ``.from_xarray`` methods, which will unpack an xarray DataArray appropriately.

**Comment by jlstevens** [comment]
Looks great! My only question is whether you think there is a difference between ``from_X`` and ``load_X``. Why not ``load_xarray`` to be consistent?

**Comment by philippjfr** [comment]
Because it doesn't load any xarray file, only ones that can be loaded with ``xr.open_rasterio`` and I'm not quite sure what else xr.open_rasterio works on.

**Pull request merged**
